version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            #curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            #tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            #mv -f /tmp/docker/* /usr/bin
      - run:
          name: Pull the image
          command: |
            TAG=$CIRCLE_BUILD_NUM
            pwd
            cd .circleci 
            docker build -t myimage:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push overgear/og-backend/myimage:$TAG
      - save_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  test:
    docker:
      - image: library/node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - run: echo "hello world"
      - save_cache:
          key: test-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build
