version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            #curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            #tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            #sudo /tmp/docker/dockerd -H fd://
            sudo ps ax|grep dockerd
            sudo cat /var/run/docker.pid
            TAG=$CIRCLE_BUILD_NUM
            IMAGE=overgear/og-backend/myimage:$TAG
            cd .circleci
            sudo /usr/bin/docker build -t $IMAGE .
            sudo /usr/bin/docker login -u $DOCKER_USER -p $DOCKER_PASS
            sudo /usr/bin/docker push $IMAGE
      
  test:
    docker:
      - image: library/node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - run: echo "hello world"
      - save_cache:
          key: test-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build
